site_name: CASLAB
site_url: https://caslab.cmpe.boun.edu.tr/
site_description: "Computer Architecture and Systems Laboratory at Boğaziçi University"
site_author: bouncmpe

copyright: Copyright &copy; 1982 - 2023 Department of Computer Engineering

docs_dir: content
repo_name: bouncmpe/caslab
repo_url: https://github.com/bouncmpe/caslab
edit_uri: edit/main/content/

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    edit: material/pencil 
    view: material/eye
  language: "en"
  font:
    text: Inter
  palette:
    scheme: south-campus
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.action.edit
    - content.action.view

plugins:
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: true
  - search:
      lang:
        - en
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - meta
  - tables
  - toc:
      permalink: "#"
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 3
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Bogazici_CmpE
    - icon: fontawesome/brands/github
      link: https://github.com/bouncmpe

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home:
      - index.md
  - People:
      - people/index.md
  - Theses:
      - theses/index.md
      - Doctoral Theses: []
      - Masters Theses:
        - theses/bilgili.md
        - theses/ulus.md
  - Courses:
      - courses/index.md
  - Tools:
      - tools/index.md